export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const LOAD_CHART_SUCCESS = 'LOAD_CHART_SUCCESS';
export const FETCH_USER_FULFILLED = 'FETCH_USER_FULFILLED';
export const GET_DATA = 'GET_DATA';

//sagas action types
export const FETCH_ASYNC_SAGA_DATA = 'FETCH_ASYNC_SAGA_DATA';
export const FETCH_SAGA_INITIATED = 'FETCH_SAGA_INITIATED';
export const FETCH_SAGA_DATA_SUCCESS = 'FETCH_SAGA_DATA_SUCCESS';
export const FETCH_SAGA_DATA_ERROR = 'FETCH_SAGA_DATA_ERROR';






